export const uiTokens = {
  colors: {
    pageBg: '#f6f7f9',
    surface: '#ffffff',
    subtleSurface: '#f8fafc',
    hoverSurface: '#f4f7fb',
    selectedSurface: '#eaf0fb',
    textStrong: '#111827',
    textBody: '#374151',
    textMuted: '#6b7280',
    borderDefault: '#e5e7eb',
    borderSoft: '#eef2f7',
    borderStrong: '#dfe4ea',
    primary: '#111827',
    onPrimary: '#ffffff',
    neutralBadgeBg: '#f3f4f6',
    neutralBadgeText: '#374151',
    infoBadgeBg: '#eef2ff',
    infoBadgeText: '#3730a3',
    infoBadgeBorder: '#c7d2fe',
    successBadgeBg: '#ecfdf5',
    successBadgeText: '#065f46',
    successBadgeBorder: '#a7f3d0',
    warningBadgeBg: '#fffbeb',
    warningBadgeText: '#92400e',
    warningBadgeBorder: '#fde68a',
    errorBadgeBg: '#fef2f2',
    errorBadgeText: '#991b1b',
    errorBadgeBorder: '#fecaca',
    overlay: 'rgba(17, 24, 39, 0.45)',
    shadow: 'rgba(17, 24, 39, 0.12)',
  },
  spacing: {
    xxs: '4px',
    xs: '6px',
    sm: '8px',
    md: '10px',
    lg: '12px',
    xl: '14px',
    xxl: '16px',
  },
  typography: {
    xs: '12px',
    sm: '13px',
    md: '14px',
    title: '18px',
    titleWeight: 700,
    strongWeight: 600,
  },
  radius: {
    control: '10px',
    card: '12px',
    modal: '16px',
    pill: '999px',
  },
} as const

export type BadgeTone = 'neutral' | 'info' | 'success' | 'warning' | 'error'
